version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-filmography
    environment:
      POSTGRES_DB: filmography
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d  
      - postgres-data:/var/lib/postgresql/data    

volumes:
  postgres-data: